server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: ms1-incidents
          uri: https://flakily-rotunda-skid.ngrok-free.dev # Pointe vers le MS1 lointain
          predicates:
            - Path=/api/incidents/**
            
        - id: ms2-affectations
          uri: http://localhost:8082 # MS2 actuel qui tourne localement
          predicates:
            - Path=/api/affectations/**
            
        - id: ms3-users
          uri: https://doorstep-bobsled-nutrient.ngrok-free.dev # MS Users (techniciens/equipes)
          predicates:
            - Path=/api/utilisateurs/**, /api/equipes/**

        - id: ms4-notifications
          uri: https://knapsack-cesspool-gangly.ngrok-free.dev # MS Notifications
          predicates:
            - Path=/api/notifications/**
