# Port spécifique pour ton microservice MS5
server.port=8085
spring.application.name=ms5-notifications

# Configuration de la base de données (PostgreSQL)
# Remplace 'notifications_db' par le nom de ta base
# Remplace 'postgres' et 'ton_mot_de_passe' par tes vrais identifiants
spring.datasource.url=jdbc:postgresql://localhost:5432/notifications_db
spring.datasource.username=postgres
spring.datasource.password=Drrt@2026

# Hibernate : crée les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect